#!/usr/bin/env bash
set -euo pipefail

# ─── BLITE Self-Host Setup ───────────────────────────────────────────────────
# Interactive setup script that configures and launches a self-hosted BLITE
# instance. Requires Docker and Docker Compose.
# ─────────────────────────────────────────────────────────────────────────────

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

info()  { echo -e "${GREEN}[✓]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
error() { echo -e "${RED}[✗]${NC} $*"; }

echo ""
echo -e "${BOLD}  ╔══════════════════════════════════╗${NC}"
echo -e "${BOLD}  ║       BLITE Self-Host Setup       ║${NC}"
echo -e "${BOLD}  ╚══════════════════════════════════╝${NC}"
echo ""

# ─── Check Docker ────────────────────────────────────────────────────────────

if ! command -v docker &>/dev/null; then
  error "Docker is not installed."
  echo "  Install it from: https://docs.docker.com/engine/install/"
  exit 1
fi

if ! docker compose version &>/dev/null && ! docker-compose version &>/dev/null; then
  error "Docker Compose is not installed."
  echo "  Install it from: https://docs.docker.com/compose/install/"
  exit 1
fi

# Prefer 'docker compose' (v2) over 'docker-compose' (v1)
if docker compose version &>/dev/null; then
  COMPOSE="docker compose"
else
  COMPOSE="docker-compose"
fi

info "Docker and Docker Compose detected"

# ─── Detect public IP ───────────────────────────────────────────────────────

PUBLIC_IP=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || echo "")
if [ -z "$PUBLIC_IP" ]; then
  PUBLIC_IP="127.0.0.1"
  warn "Could not detect public IP, defaulting to 127.0.0.1"
else
  info "Detected public IP: $PUBLIC_IP"
fi

# ─── Ask: Domain or IP ──────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}Domain Configuration${NC}"
echo "  If you have a domain pointing to this server, enter it below."
echo "  Otherwise, press Enter to use your IP address ($PUBLIC_IP)."
echo ""
read -rp "  Domain (or press Enter for IP): " DOMAIN

if [ -z "$DOMAIN" ]; then
  DOMAIN=""
  SERVER_URL="http://${PUBLIC_IP}:3001"
  CORS_ORIGIN="*"
  USE_CADDY=false
  info "Using IP-based access: $SERVER_URL"
else
  SERVER_URL="https://${DOMAIN}"
  CORS_ORIGIN="https://${DOMAIN}"
  USE_CADDY=true
  info "Using domain: $DOMAIN (Caddy will auto-provision HTTPS)"
fi

# ─── Ask: Full or Lite mode ─────────────────────────────────────────────────

echo ""
echo -e "${BOLD}Mode Selection${NC}"
echo "  ${GREEN}full${NC}  — Text chat + voice/video calls (requires UDP ports 40000-40100)"
echo "  ${GREEN}lite${NC}  — Text chat only, no voice/video (simpler, no UDP ports needed)"
echo ""
read -rp "  Mode [full/lite] (default: lite): " MODE_INPUT

BLITE_MODE="${MODE_INPUT:-lite}"
if [ "$BLITE_MODE" != "full" ] && [ "$BLITE_MODE" != "lite" ]; then
  BLITE_MODE="lite"
fi
info "Mode: $BLITE_MODE"

# ─── Generate secrets ───────────────────────────────────────────────────────

JWT_SECRET=$(openssl rand -base64 48 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -d '\n')
info "Generated JWT secret"

# ─── Write .env ──────────────────────────────────────────────────────────────

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  warn "Existing .env found — backing up to .env.backup"
  cp "$ENV_FILE" ".env.backup"
fi

cat > "$ENV_FILE" <<EOF
# BLITE Self-Hosted Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Server
PORT=3001
SERVER_URL=${SERVER_URL}
JWT_SECRET=${JWT_SECRET}
CORS_ORIGIN=${CORS_ORIGIN}
NODE_ENV=production

# Mode: 'full' (voice+video) or 'lite' (text only)
BLITE_MODE=${BLITE_MODE}

# Docker port mapping
BLITE_PORT=3001

# mediasoup (only used in full mode)
MEDIASOUP_ANNOUNCED_IP=${PUBLIC_IP}
MEDIASOUP_RTC_MIN_PORT=40000
MEDIASOUP_RTC_MAX_PORT=40100
MEDIASOUP_NUM_WORKERS=auto
EOF

# Add domain to .env if using Caddy
if [ "$USE_CADDY" = true ]; then
  echo "" >> "$ENV_FILE"
  echo "# Caddy reverse proxy" >> "$ENV_FILE"
  echo "DOMAIN=${DOMAIN}" >> "$ENV_FILE"
fi

info "Wrote $ENV_FILE"

# ─── Enable Caddy in docker-compose if domain is set ────────────────────────

if [ "$USE_CADDY" = true ]; then
  info "Caddy reverse proxy will handle HTTPS for $DOMAIN"
  echo ""
  warn "Make sure your domain's DNS A record points to $PUBLIC_IP"
  echo "  Caddy will auto-provision a Let's Encrypt certificate on first request."
  echo ""
  echo "  To enable Caddy, uncomment the caddy service in docker-compose.yml"
  echo "  and the caddy-data/caddy-config volumes, then run:"
  echo "    $COMPOSE up -d"
fi

# ─── Build and start ────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}Starting BLITE...${NC}"
$COMPOSE up -d --build

echo ""
echo -e "${BOLD}  ╔══════════════════════════════════╗${NC}"
echo -e "${BOLD}  ║         BLITE is running!         ║${NC}"
echo -e "${BOLD}  ╚══════════════════════════════════╝${NC}"
echo ""
info "Access BLITE at: $SERVER_URL"
if [ "$BLITE_MODE" = "lite" ]; then
  info "Running in lite mode (text + E2EE + file sharing)"
else
  info "Running in full mode (text + voice/video + E2EE + file sharing)"
  warn "Ensure UDP ports 40000-40100 are open in your firewall"
fi
echo ""
info "Useful commands:"
echo "    $COMPOSE logs -f        # View logs"
echo "    $COMPOSE down           # Stop BLITE"
echo "    $COMPOSE up -d          # Start BLITE"
echo "    $COMPOSE pull && $COMPOSE up -d --build  # Update"
echo ""
